import Navbar from "@/components/navbar/Navbar";
import "./globals.css";
import type { Metadata } from "next";

export const metadata: Metadata = {
  title: "Create Next App",
  description: "Generated by create next app",
};

export default function RootLayout({
  children,
}: {
  children: React.ReactNode;
}) {

  return (
    <html lang="en">
      {/* Navbar has fixed height and possition (64px at top 0) so everything must be bellow that */}
      <body className="h-full mt-16"> 
        <Navbar />
        {children}
      </body>
    </html>
  );
}
